### PR TITLE
Add gradient communication quantization (GCQ)

### PR DESCRIPTION
**Pull request by HandH1998**
I make a new directory at lightseq/training/gradient_comm_quantization, where I put GCQ code. The main change is at trainer.py, where I register communication hook to conduct GCQ.

### CODE REVIEW

**Comment by HandH1998** [comment]
I make a new directory at lightseq/training/gcq, where I put GCQ code. GCQ has supported huggingface and fairseq.

**Comment by HandH1998** [comment]
I  have optimized GCQ code for Fairseq and Hugging Face.

**Comment by HandH1998** [comment]
Optimize code again.

**Comment by HandH1998** [comment]
Add torch version check.

**Review by Taka152 — APPROVED** [review]

**Pull request merged**
